### ISSUE TITLE
JString is broken (utf8 to utf16 conversion and vice versa)

### ISSUE THREAD

**Issue by ChristopherHX** [dukeify/fake-jni#105]
Expected behavior:
- creating a JString with a UTF-8 string (char*)
- get a string with getStringUTFChars returns a multibyte sequence
- get the same string with getStringChars **return a utf-16 sequence**

Actual behaviour:
- creating a JString with a UTF-8 string (char*)
- get a string with getStringUTFChars returns a multibyte sequence
- get the same string with getStringChars **returns a multibyte sequence, now just casted to utf-16 type**

Following code causes this behaviour
One of should convert the sequence, or remember it's codepage
- https://github.com/dukeify/fake-jni/blob/3be5c1c4a0472f52d7dd51581b2b2dd54e0f506e/src/jni/native/string.cpp#L27
https://github.com/dukeify/fake-jni/blob/3be5c1c4a0472f52d7dd51581b2b2dd54e0f506e/src/jni/native/string.cpp#L53

- https://github.com/dukeify/fake-jni/blob/3be5c1c4a0472f52d7dd51581b2b2dd54e0f506e/src/jvm/string.cpp#L24
https://github.com/dukeify/fake-jni/blob/3be5c1c4a0472f52d7dd51581b2b2dd54e0f506e/src/jvm/string.cpp#L28

I'm aware that jni spec is not using UTF-8, but UCS-8.

**This issue also applies to the minecraft-linux fork, which I need to fix to get the xboxlive working again.**

**Comment by ChristopherHX** [comment]
getStringChars should be nullterminated, because new microsofts xboxlive depends on this property to be true.
So Android's jvm have to do it the same way.

- create a JString((jchar*)u"1.16.20.03", 10) 
- getStringChars returns u"1.16.2" (non null terminated)

**Comment by luser** [comment]
The JNI docs are extremely unclear here but some brief research indicates that `getStringChars` does not guarantee that the string returned is null-terminated. `getStringUTFChars` does guarantee null-termination for the UCS-8 strings it returns.

**Comment by luser** [comment]
The implementation of `JString` here is very confusing! [It inherits from `JCharArray`](https://github.com/dukeify/fake-jni/blob/3be5c1c4a0472f52d7dd51581b2b2dd54e0f506e/include/fake-jni/string.h#L8) which is an array of `jchar`, so 16-bit code units. However, as pointed out in the original comment, the constructor that takes a `char*` uses `memcpy` to copy those bytes into the internal array, which seems wrong:
https://github.com/dukeify/fake-jni/blob/3be5c1c4a0472f52d7dd51581b2b2dd54e0f506e/src/jvm/string.cpp#L22-L25

...and the constructor that takes `JChar*, JInt size` *also* uses `memcpy`, but uses `size` as the byte length of the string (it's not, it's the length of the string in 16-bit code units) and initializes the internal array to be `2*size` in length, which is twice as large as it needs to be:
https://github.com/dukeify/fake-jni/blob/3be5c1c4a0472f52d7dd51581b2b2dd54e0f506e/src/jvm/string.cpp#L27-L29

**Comment by Matthewacon** [comment]
Unfortunately the prototype version of fake-jni is no longer maintained, see the [README](https://github.com/dukeify/fake-jni/blob/master/README.md#deprecation-warning). There is a new version on the way, which should serve as a near drop-in replacement for the prototype, that does not have any of the bugs described in the issue tracker.
