### ISSUE TITLE
Catch exceptions and signals thrown inside of JNI and Agent modules and clean up all JVM resources

### ISSUE THREAD

**Issue by Matthewacon** [dukeify/fake-jni#54]
Allow for user-registered exception and signal handlers, but provide default handlers for both so that all resources are cleaned up before failing gracefully.

**Comment by Matthewacon** [comment]
Look into adding [libunwind](https://github.com/libunwind/libunwind) support to create backtraces into attached libraries when encountering a JNI or unhandled exception.

**Comment by meme** [comment]
Just note that I'm pretty sure unwinding outside of your own executable is UB, though I don't imagine it will actually cause issues (just use it with care)

**Comment by Matthewacon** [comment]
Closed as of c207a3b279a33875143bc095def29bc526f5770b.
